/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: AlmondFeather (https://sketchfab.com/almondfeather)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/mimikyu-ad2aaa7bb372441984f40df49854b3eb
title: Mimikyu
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei'

import { useAnimations } from '@react-three/drei'

export default function Mimikyu(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {    
    actions['Take 01'].play();  
  });

  useFrame(() => (group.current.rotation.y += 0.002))

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={[0.4, 0.4, 0.4]}>
          <primitive object={nodes.Armature_rootJoint} />
          <skinnedMesh
            material={materials.body}
            geometry={nodes.mimikyu_0.geometry}
            skeleton={nodes.mimikyu_0.skeleton}
          />
          <skinnedMesh
            material={materials.eyes}
            geometry={nodes.mimikyu_1.geometry}
            skeleton={nodes.mimikyu_1.skeleton}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
